import type { TimelineRole } from "./types";

export const pianoProjectRoot =
  "/Users/lionelyu/Music/Piano Hand Size Part 2";

export const sourceRelativePaths: Record<string, string> = {
  "001_IMG_0256_0142am_trip_setup.MOV":
    "01_Trip_Setup/001_IMG_0256_0142am_trip_setup.MOV",
  "002_IMG_0257_hagerstown_gas_station.MOV":
    "01_Trip_Setup/002_IMG_0257_hagerstown_gas_station.MOV",
  "003_IMG_0258_road_trip_snacks_no_caffeine.MOV":
    "01_Trip_Setup/003_IMG_0258_road_trip_snacks_no_caffeine.MOV",
  "005_IMG_0260_waking_up_after_car_nap.MOV":
    "01_Trip_Setup/005_IMG_0260_waking_up_after_car_nap.MOV",
  "006_IMG_0261_car_nap_recovery_drive_resumes.MOV":
    "01_Trip_Setup/006_IMG_0261_car_nap_recovery_drive_resumes.MOV",
  "007_IMG_0263_morning_highway_update.MOV":
    "02_Drive_To_Titusville/007_IMG_0263_morning_highway_update.MOV",
  "008_IMG_0264_pennsylvania_scenery.MOV":
    "02_Drive_To_Titusville/008_IMG_0264_pennsylvania_scenery.MOV",
  "009_IMG_0265_drive_broll_1.MOV":
    "02_Drive_To_Titusville/009_IMG_0265_drive_broll_1.MOV",
  "010_IMG_0266_drive_broll_2.MOV":
    "02_Drive_To_Titusville/010_IMG_0266_drive_broll_2.MOV",
  "011_IMG_0267_in_the_woods_almost_there.MOV":
    "02_Drive_To_Titusville/011_IMG_0267_in_the_woods_almost_there.MOV",
  "012_IMG_0268_double_big_mac_lunch.MOV":
    "02_Drive_To_Titusville/012_IMG_0268_double_big_mac_lunch.MOV",
  "013_IMG_0269_keyboard_21_intro.MOV":
    "03_David_Factory_Visit/013_IMG_0269_keyboard_21_intro.MOV",
  "018_IMG_0274_ds_size_lineup_on_steinway.MOV":
    "03_David_Factory_Visit/018_IMG_0274_ds_size_lineup_on_steinway.MOV",
  "019_IMG_0275_ds55_pickup_and_wrap.MOV":
    "03_David_Factory_Visit/019_IMG_0275_ds55_pickup_and_wrap.MOV",
  "027_IMG_0283_athena_internals_reconnaissance.MOV":
    "03_David_Factory_Visit/027_IMG_0283_athena_internals_reconnaissance.MOV",
  "041_IMG_0297_ds60_ds55_car_monologue.MOV":
    "05_Post_Pickup_Main_Argument/041_IMG_0297_ds60_ds55_car_monologue.MOV",
  "042_IMG_0298_tionesta_lake_cutaway.MOV":
    "05_Post_Pickup_Main_Argument/042_IMG_0298_tionesta_lake_cutaway.MOV",
  "043_IMG_0299_lake_overlook_broll.MOV":
    "05_Post_Pickup_Main_Argument/043_IMG_0299_lake_overlook_broll.MOV",
  "044_IMG_0300_177777_mileage.MOV":
    "05_Post_Pickup_Main_Argument/044_IMG_0300_177777_mileage.MOV",
  "048_IMG_0304_hotel_car_broke_down.MOV":
    "06_Car_Trouble_Return/048_IMG_0304_hotel_car_broke_down.MOV",
  "049_IMG_0305_car_fixed_heading_home.MOV":
    "06_Car_Trouble_Return/049_IMG_0305_car_fixed_heading_home.MOV",
  "050_IMG_0306_beautiful_return_drive.MOV":
    "06_Car_Trouble_Return/050_IMG_0306_beautiful_return_drive.MOV",
  "053_IMG_0309_highway_home_broll.MOV":
    "06_Car_Trouble_Return/053_IMG_0309_highway_home_broll.MOV",
  "054_IMG_0310_home_ds60_ds55_explanation.MOV":
    "07_Home_Demo_Payoff/054_IMG_0310_home_ds60_ds55_explanation.MOV",
  "055_PICKUP_front_facing_intro.MOV":
    "08_Pickups_To_Record/055_PICKUP_front_facing_intro.MOV",
  "056_PICKUP_hand_key_comparison.MOV":
    "08_Pickups_To_Record/056_PICKUP_hand_key_comparison.MOV",
  "technical-keyboard-stills":
    "04_Keyboards_Technical_Stills/030_IMG_0286_technical_keyboard_still.JPG",
};

export type SeedTimelineItem = {
  id: string;
  source: string;
  section: string;
  targetDuration: number;
  role: TimelineRole;
  sourceIn?: number;
  sourceOut?: number;
  textOverlay?: string;
  notes: string;
};

export const timelineSeed: SeedTimelineItem[] = [
  {
    id: "tl-001-late-night-trip-setup",
    source: "001_IMG_0256_0142am_trip_setup.MOV",
    section: "Cold Open",
    targetDuration: 8,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 15,
    notes: "Late-night selfie: 1:42 a.m. and driving to Titusville.",
  },
  {
    id: "tl-002-car-broke-flashforward",
    source: "048_IMG_0304_hotel_car_broke_down.MOV",
    section: "Cold Open",
    targetDuration: 5,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 8,
    notes: "Hard flash-forward to hotel because the car broke down.",
  },
  {
    id: "tl-003-home-payoff-flash",
    source: "054_IMG_0310_home_ds60_ds55_explanation.MOV",
    section: "Cold Open",
    targetDuration: 8,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 23,
    notes: "Flash home payoff: DS 6.0 and DS 5.5, keys are what matter.",
  },
  {
    id: "tl-004-p056-cold-open",
    source: "056_PICKUP_hand_key_comparison.MOV",
    section: "Cold Open",
    targetDuration: 3,
    role: "placeholder",
    textOverlay: "P056",
    notes: "Placeholder for clean hand/key comparison.",
  },
  {
    id: "tl-005-cold-open-title",
    source: "title-card-road-keyboard",
    section: "Cold Open",
    targetDuration: 6,
    role: "title_card",
    textOverlay:
      "I drove overnight for a keyboard most pianists have never tried.",
    notes: "Text over road or keyboard b-roll.",
  },
  {
    id: "tl-006-front-facing-intro",
    source: "055_PICKUP_front_facing_intro.MOV",
    section: "Set Up",
    targetDuration: 20,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 30,
    notes: "Clean intro: Pennsylvania, DS 6.0, DS 5.5, and why sizes matter.",
  },
  {
    id: "tl-007-size-difference-practice",
    source: "001_IMG_0256_0142am_trip_setup.MOV",
    section: "Set Up",
    targetDuration: 10,
    role: "a_roll",
    sourceIn: 41,
    sourceOut: 54,
    notes: "Size difference changes practicing; cover with key-size stills.",
  },
  {
    id: "tl-008-ds-size-lineup-setup",
    source: "018_IMG_0274_ds_size_lineup_on_steinway.MOV",
    section: "Set Up",
    targetDuration: 15,
    role: "b_roll",
    sourceIn: 49,
    sourceOut: 72,
    textOverlay: "Standard / DS 6.0 / DS 5.5 / DS 5.1 / DS 4.0",
    notes: "Introduce the size lineup with labels.",
  },
  {
    id: "tl-009-drive-proof",
    source: "001_IMG_0256_0142am_trip_setup.MOV",
    section: "Overnight Drive",
    targetDuration: 8,
    role: "a_roll",
    sourceIn: 17,
    sourceOut: 27,
    notes: "Time proof and five-and-a-half-hour drive.",
  },
  {
    id: "tl-010-hagerstown-gas",
    source: "002_IMG_0257_hagerstown_gas_station.MOV",
    section: "Overnight Drive",
    targetDuration: 10,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 12,
    notes: "Gas station near Hagerstown; snacks setup.",
  },
  {
    id: "tl-011-snack-montage",
    source: "003_IMG_0258_road_trip_snacks_no_caffeine.MOV",
    section: "Overnight Drive",
    targetDuration: 25,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 136,
    notes: "Fast snack montage: water, beef stick, chocolate milk, no caffeine.",
  },
  {
    id: "tl-012-rainy-drive",
    source: "010_IMG_0266_drive_broll_2.MOV",
    section: "Overnight Drive",
    targetDuration: 10,
    role: "ambient",
    sourceIn: 0,
    sourceOut: 15,
    notes: "Rain, wipers, gray highway fatigue.",
  },
  {
    id: "tl-013-car-nap",
    source: "005_IMG_0260_waking_up_after_car_nap.MOV",
    section: "Overnight Drive",
    targetDuration: 8,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 8,
    notes: "Waking up after sleeping in the back.",
  },
  {
    id: "tl-014-drive-resumes",
    source: "006_IMG_0261_car_nap_recovery_drive_resumes.MOV",
    section: "Overnight Drive",
    targetDuration: 12,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 36,
    notes: "Almost three hours of sleep; keep driving.",
  },
  {
    id: "tl-015-morning-highway",
    source: "007_IMG_0263_morning_highway_update.MOV",
    section: "Pennsylvania Road",
    targetDuration: 16,
    role: "a_roll",
    sourceIn: 21,
    sourceOut: 44,
    notes: "Called David, three and a half hours left, feeling energetic.",
  },
  {
    id: "tl-016-pennsylvania-scenery",
    source: "008_IMG_0264_pennsylvania_scenery.MOV",
    section: "Pennsylvania Road",
    targetDuration: 10,
    role: "ambient",
    sourceIn: 0,
    sourceOut: 16,
    notes: "Scenic road montage; let it breathe.",
  },
  {
    id: "tl-017-drive-broll-hills",
    source: "009_IMG_0265_drive_broll_1.MOV",
    section: "Pennsylvania Road",
    targetDuration: 10,
    role: "ambient",
    sourceIn: 0,
    sourceOut: 16,
    notes: "Highway and hill b-roll under music.",
  },
  {
    id: "tl-018-woods-almost-there",
    source: "011_IMG_0267_in_the_woods_almost_there.MOV",
    section: "Pennsylvania Road",
    targetDuration: 18,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 20,
    notes: "In the woods and almost there.",
  },
  {
    id: "tl-019-big-mac-gag",
    source: "012_IMG_0268_double_big_mac_lunch.MOV",
    section: "Pennsylvania Road",
    targetDuration: 4,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 6,
    notes: "Optional quick hunger gag.",
  },
  {
    id: "tl-020-keyboard-21-arrival",
    source: "013_IMG_0269_keyboard_21_intro.MOV",
    section: "Factory",
    targetDuration: 8,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 7,
    notes: "Arrival: keyboard number 21.",
  },
  {
    id: "tl-021-keyboard-action-broll",
    source: "013_IMG_0269_keyboard_21_intro.MOV",
    section: "Factory",
    targetDuration: 14,
    role: "b_roll",
    sourceIn: 0,
    sourceOut: 40,
    notes: "Exposed action, keys, and workshop proof.",
  },
  {
    id: "tl-022-ds55-on-steinway",
    source: "018_IMG_0274_ds_size_lineup_on_steinway.MOV",
    section: "Factory",
    targetDuration: 30,
    role: "b_roll",
    sourceIn: 0,
    sourceOut: 43,
    notes: "DS 5.5 on Steinway B and DS 4.0 range.",
  },
  {
    id: "tl-023-size-lineup-proof",
    source: "018_IMG_0274_ds_size_lineup_on_steinway.MOV",
    section: "Factory",
    targetDuration: 20,
    role: "b_roll",
    sourceIn: 49,
    sourceOut: 72,
    textOverlay: "DS size lineup",
    notes: "Clearest size-comparison proof.",
  },
  {
    id: "tl-024-ds55-pickup-playing",
    source: "019_IMG_0275_ds55_pickup_and_wrap.MOV",
    section: "Factory",
    targetDuration: 27,
    role: "b_roll",
    sourceIn: 0,
    sourceOut: 150,
    notes: "DS 5.5 identification plus hands-on playing/testing.",
  },
  {
    id: "tl-025-athena-internals",
    source: "027_IMG_0283_athena_internals_reconnaissance.MOV",
    section: "Factory",
    targetDuration: 35,
    role: "b_roll",
    sourceIn: 0,
    sourceOut: 64,
    notes: "Technical tour: sound module, board, speakers, internals.",
  },
  {
    id: "tl-026-technical-stills",
    source: "technical-keyboard-stills",
    section: "Factory",
    targetDuration: 15,
    role: "still",
    notes: "Freeze-frame inserts of keys, action, and internals.",
  },
  {
    id: "tl-027-leaving-factory",
    source: "041_IMG_0297_ds60_ds55_car_monologue.MOV",
    section: "Main Argument",
    targetDuration: 20,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 36,
    notes: "Leaving with DS 6.0 and DS 5.5.",
  },
  {
    id: "tl-028-full-size-strain",
    source: "041_IMG_0297_ds60_ds55_car_monologue.MOV",
    section: "Main Argument",
    targetDuration: 27,
    role: "a_roll",
    sourceIn: 36,
    sourceOut: 77,
    textOverlay: "MY EXPERIENCE / FOR MY HAND SIZE",
    notes: "Full-size keyboard created strained wrist-based technique.",
  },
  {
    id: "tl-029-smaller-keys-technique",
    source: "041_IMG_0297_ds60_ds55_car_monologue.MOV",
    section: "Main Argument",
    targetDuration: 28,
    role: "a_roll",
    sourceIn: 94,
    sourceOut: 125,
    notes: "Smaller keys help intervals and finger technique.",
  },
  {
    id: "tl-030-healthier-foundation",
    source: "041_IMG_0297_ds60_ds55_car_monologue.MOV",
    section: "Main Argument",
    targetDuration: 28,
    role: "a_roll",
    sourceIn: 125,
    sourceOut: 151,
    notes: "Changes the piano experience; healthier foundation and less strain.",
  },
  {
    id: "tl-031-ds-standard-universities",
    source: "041_IMG_0297_ds60_ds55_car_monologue.MOV",
    section: "Main Argument",
    targetDuration: 37,
    role: "a_roll",
    sourceIn: 192,
    sourceOut: 227,
    textOverlay: "DS standard",
    notes: "DS standard and university use as a differentiating factor.",
  },
  {
    id: "tl-032-lake-transition",
    source: "042_IMG_0298_tionesta_lake_cutaway.MOV",
    section: "Trip Fights Back",
    targetDuration: 7,
    role: "ambient",
    sourceIn: 0,
    sourceOut: 9,
    notes: "Calm lake transition after dense argument.",
  },
  {
    id: "tl-033-lake-overlook",
    source: "043_IMG_0299_lake_overlook_broll.MOV",
    section: "Trip Fights Back",
    targetDuration: 6,
    role: "ambient",
    sourceIn: 0,
    sourceOut: 18,
    notes: "Overlook b-roll under music.",
  },
  {
    id: "tl-034-mileage-beat",
    source: "044_IMG_0300_177777_mileage.MOV",
    section: "Trip Fights Back",
    targetDuration: 4,
    role: "b_roll",
    sourceIn: 0,
    sourceOut: 6,
    notes: "Tiny weird road beat; optional.",
  },
  {
    id: "tl-035-hotel-breakdown",
    source: "048_IMG_0304_hotel_car_broke_down.MOV",
    section: "Trip Fights Back",
    targetDuration: 20,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 42,
    notes: "Hotel, car broke down, saga continues.",
  },
  {
    id: "tl-036-car-fixed",
    source: "049_IMG_0305_car_fixed_heading_home.MOV",
    section: "Trip Fights Back",
    targetDuration: 16,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 19,
    notes: "Car fixed; loose battery connection.",
  },
  {
    id: "tl-037-return-drive-beautiful",
    source: "050_IMG_0306_beautiful_return_drive.MOV",
    section: "Trip Fights Back",
    targetDuration: 6,
    role: "ambient",
    sourceIn: 0,
    sourceOut: 12,
    notes: "Beautiful return drive into home payoff.",
  },
  {
    id: "tl-038-highway-home",
    source: "053_IMG_0309_highway_home_broll.MOV",
    section: "Trip Fights Back",
    targetDuration: 6,
    role: "ambient",
    sourceIn: 0,
    sourceOut: 12,
    notes: "Highway home b-roll under music.",
  },
  {
    id: "tl-039-home-setup",
    source: "054_IMG_0310_home_ds60_ds55_explanation.MOV",
    section: "Home Payoff",
    targetDuration: 25,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 30,
    notes: "At home with DS 6.0 and DS 5.5; keys are what matter.",
  },
  {
    id: "tl-040-ds60-history",
    source: "054_IMG_0310_home_ds60_ds55_explanation.MOV",
    section: "Home Payoff",
    targetDuration: 25,
    role: "a_roll",
    sourceIn: 43,
    sourceOut: 65,
    notes: "DS 6.0 history and proper weighting.",
  },
  {
    id: "tl-041-p056-home-comparison",
    source: "056_PICKUP_hand_key_comparison.MOV",
    section: "Home Payoff",
    targetDuration: 5,
    role: "placeholder",
    textOverlay: "P056",
    notes: "Placeholder for hand/key comparison insert.",
  },
  {
    id: "tl-042-ds55-valid",
    source: "054_IMG_0310_home_ds60_ds55_explanation.MOV",
    section: "Home Payoff",
    targetDuration: 33,
    role: "a_roll",
    sourceIn: 71,
    sourceOut: 114,
    notes: "DS 5.5 is valid; smaller hands may benefit.",
  },
  {
    id: "tl-043-current-take-chart",
    source: "054_IMG_0310_home_ds60_ds55_explanation.MOV",
    section: "Home Payoff",
    targetDuration: 32,
    role: "a_roll",
    sourceIn: 126,
    sourceOut: 205,
    textOverlay: "My current take",
    notes: "Technique improved; update recommendations; try both sizes.",
  },
  {
    id: "tl-044-ds-standard-home",
    source: "054_IMG_0310_home_ds60_ds55_explanation.MOV",
    section: "Home Payoff",
    targetDuration: 35,
    role: "a_roll",
    sourceIn: 221,
    sourceOut: 296,
    textOverlay: "DS standard / university instruments",
    notes: "Why DS standard matters for serious study and universities.",
  },
  {
    id: "tl-045-closing-recommendation",
    source: "054_IMG_0310_home_ds60_ds55_explanation.MOV",
    section: "Closing",
    targetDuration: 13,
    role: "a_roll",
    sourceIn: 296,
    sourceOut: 312,
    notes: "Closing recommendation: buy a DS-sized keyboard.",
  },
  {
    id: "tl-046-final-hook",
    source: "056_PICKUP_hand_key_comparison.MOV",
    section: "Closing",
    targetDuration: 7,
    role: "placeholder",
    textOverlay: "Part 3: DS 6.0 vs DS 5.5 comparison?",
    notes: "Final still/demo placeholder until the pickup is recorded.",
  },
];
