import type { TimelineRole } from "./types";

export const pianoProjectRoot =
  "/Users/lionelyu/Music/Piano Hand Size Part 2";

export const sourceRelativePaths: Record<string, string> = {
  "001_IMG_0256_0142am_trip_setup.MOV":
    "01_Trip_Setup/001_IMG_0256_0142am_trip_setup.MOV",
  "002_IMG_0257_hagerstown_gas_station.MOV":
    "01_Trip_Setup/002_IMG_0257_hagerstown_gas_station.MOV",
  "003_IMG_0258_road_trip_snacks_no_caffeine.MOV":
    "01_Trip_Setup/003_IMG_0258_road_trip_snacks_no_caffeine.MOV",
  "004_IMG_0259_sheets_stop_middle_of_nowhere.MOV":
    "01_Trip_Setup/004_IMG_0259_sheets_stop_middle_of_nowhere.MOV",
  "005_IMG_0260_waking_up_after_car_nap.MOV":
    "01_Trip_Setup/005_IMG_0260_waking_up_after_car_nap.MOV",
  "006_IMG_0261_car_nap_recovery_drive_resumes.MOV":
    "01_Trip_Setup/006_IMG_0261_car_nap_recovery_drive_resumes.MOV",
  "007_IMG_0263_morning_highway_update.MOV":
    "02_Drive_To_Titusville/007_IMG_0263_morning_highway_update.MOV",
  "008_IMG_0264_pennsylvania_scenery.MOV":
    "02_Drive_To_Titusville/008_IMG_0264_pennsylvania_scenery.MOV",
  "009_IMG_0265_drive_broll_1.MOV":
    "02_Drive_To_Titusville/009_IMG_0265_drive_broll_1.MOV",
  "010_IMG_0266_drive_broll_2.MOV":
    "02_Drive_To_Titusville/010_IMG_0266_drive_broll_2.MOV",
  "011_IMG_0267_in_the_woods_almost_there.MOV":
    "02_Drive_To_Titusville/011_IMG_0267_in_the_woods_almost_there.MOV",
  "012_IMG_0268_double_big_mac_lunch.MOV":
    "02_Drive_To_Titusville/012_IMG_0268_double_big_mac_lunch.MOV",
  "013_IMG_0269_keyboard_21_intro.MOV":
    "03_David_Factory_Visit/013_IMG_0269_keyboard_21_intro.MOV",
  "018_IMG_0274_ds_size_lineup_on_steinway.MOV":
    "03_David_Factory_Visit/018_IMG_0274_ds_size_lineup_on_steinway.MOV",
  "019_IMG_0275_ds55_pickup_and_wrap.MOV":
    "03_David_Factory_Visit/019_IMG_0275_ds55_pickup_and_wrap.MOV",
  "027_IMG_0283_athena_internals_reconnaissance.MOV":
    "03_David_Factory_Visit/027_IMG_0283_athena_internals_reconnaissance.MOV",
  "041_IMG_0297_ds60_ds55_car_monologue.MOV":
    "05_Post_Pickup_Main_Argument/041_IMG_0297_ds60_ds55_car_monologue.MOV",
  "042_IMG_0298_tionesta_lake_cutaway.MOV":
    "05_Post_Pickup_Main_Argument/042_IMG_0298_tionesta_lake_cutaway.MOV",
  "043_IMG_0299_lake_overlook_broll.MOV":
    "05_Post_Pickup_Main_Argument/043_IMG_0299_lake_overlook_broll.MOV",
  "044_IMG_0300_177777_mileage.MOV":
    "05_Post_Pickup_Main_Argument/044_IMG_0300_177777_mileage.MOV",
  "048_IMG_0304_hotel_car_broke_down.MOV":
    "06_Car_Trouble_Return/048_IMG_0304_hotel_car_broke_down.MOV",
  "049_IMG_0305_car_fixed_heading_home.MOV":
    "06_Car_Trouble_Return/049_IMG_0305_car_fixed_heading_home.MOV",
  "050_IMG_0306_beautiful_return_drive.MOV":
    "06_Car_Trouble_Return/050_IMG_0306_beautiful_return_drive.MOV",
  "053_IMG_0309_highway_home_broll.MOV":
    "06_Car_Trouble_Return/053_IMG_0309_highway_home_broll.MOV",
  "054_IMG_0310_home_ds60_ds55_explanation.MOV":
    "07_Home_Demo_Payoff/054_IMG_0310_home_ds60_ds55_explanation.MOV",
  "055_PICKUP_front_facing_intro.MOV":
    "08_Pickups_To_Record/055_PICKUP_front_facing_intro.MOV",
  "056_PICKUP_hand_key_comparison.MOV":
    "08_Pickups_To_Record/056_PICKUP_hand_key_comparison.MOV",
  "technical-keyboard-stills":
    "04_Keyboards_Technical_Stills/030_IMG_0286_technical_keyboard_still.JPG",
};

export type SeedTimelineItem = {
  id: string;
  source: string;
  section: string;
  targetDuration: number;
  role: TimelineRole;
  sourceIn?: number;
  sourceOut?: number;
  rotationOverride?: 0 | 90 | 180 | 270;
  textOverlay?: string;
  notes: string;
};

export const timelineSeed: SeedTimelineItem[] = [
  {
    id: "tl-001-late-night-trip-setup",
    source: "001_IMG_0256_0142am_trip_setup.MOV",
    section: "Cold Open",
    targetDuration: 8,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 15,
    notes: "Late-night selfie: 1:42 a.m. and driving to Titusville.",
  },
  {
    id: "tl-002-car-broke-flashforward",
    source: "048_IMG_0304_hotel_car_broke_down.MOV",
    section: "Cold Open",
    targetDuration: 5,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 8,
    notes: "Hard flash-forward to hotel because the car broke down.",
  },
  {
    id: "tl-003-home-payoff-flash",
    source: "054_IMG_0310_home_ds60_ds55_explanation.MOV",
    section: "Cold Open",
    targetDuration: 8,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 23,
    notes: "Flash home payoff: DS 6.0 and DS 5.5, keys are what matter.",
  },
  {
    id: "tl-004-p056-cold-open",
    source: "056_PICKUP_hand_key_comparison.MOV",
    section: "Cold Open",
    targetDuration: 3,
    role: "placeholder",
    textOverlay: "P056",
    notes: "Placeholder for clean hand/key comparison.",
  },
  {
    id: "tl-005-cold-open-title",
    source: "title-card-road-keyboard",
    section: "Cold Open",
    targetDuration: 6,
    role: "title_card",
    textOverlay:
      "I drove overnight for a keyboard most pianists have never tried.",
    notes: "Text over road or keyboard b-roll.",
  },
  {
    id: "tl-006-front-facing-intro",
    source: "055_PICKUP_front_facing_intro.MOV",
    section: "Set Up",
    targetDuration: 20,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 30,
    notes: "Clean intro: Pennsylvania, DS 6.0, DS 5.5, and why sizes matter.",
  },
  {
    id: "tl-007-size-difference-practice",
    source: "001_IMG_0256_0142am_trip_setup.MOV",
    section: "Set Up",
    targetDuration: 10,
    role: "a_roll",
    sourceIn: 41,
    sourceOut: 54,
    notes: "Size difference changes practicing; cover with key-size stills.",
  },
  {
    id: "tl-008-ds-size-lineup-setup",
    source: "018_IMG_0274_ds_size_lineup_on_steinway.MOV",
    section: "Set Up",
    targetDuration: 15,
    role: "b_roll",
    sourceIn: 49,
    sourceOut: 72,
    textOverlay: "Standard / DS 6.0 / DS 5.5 / DS 5.1 / DS 4.0",
    notes: "Introduce the size lineup with labels.",
  },
  {
    id: "tl-009-drive-proof",
    source: "001_IMG_0256_0142am_trip_setup.MOV",
    section: "Overnight Drive",
    targetDuration: 8,
    role: "a_roll",
    sourceIn: 17,
    sourceOut: 27,
    notes: "Time proof and five-and-a-half-hour drive.",
  },
  {
    id: "tl-010-hagerstown-gas",
    source: "002_IMG_0257_hagerstown_gas_station.MOV",
    section: "Overnight Drive",
    targetDuration: 10,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 12,
    notes: "Gas station near Hagerstown; snacks setup.",
  },
  {
    id: "tl-011-snack-montage",
    source: "003_IMG_0258_road_trip_snacks_no_caffeine.MOV",
    section: "Overnight Drive",
    targetDuration: 25,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 136,
    notes: "Fast snack montage: water, beef stick, chocolate milk, no caffeine.",
  },
  {
    id: "tl-012-rainy-drive",
    source: "010_IMG_0266_drive_broll_2.MOV",
    section: "Overnight Drive",
    targetDuration: 10,
    role: "ambient",
    sourceIn: 0,
    sourceOut: 15,
    notes: "Rain, wipers, gray highway fatigue.",
  },
  {
    id: "tl-013-car-nap",
    source: "005_IMG_0260_waking_up_after_car_nap.MOV",
    section: "Overnight Drive",
    targetDuration: 8,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 8,
    notes: "Waking up after sleeping in the back.",
  },
  {
    id: "tl-014-drive-resumes",
    source: "006_IMG_0261_car_nap_recovery_drive_resumes.MOV",
    section: "Overnight Drive",
    targetDuration: 12,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 36,
    notes: "Almost three hours of sleep; keep driving.",
  },
  {
    id: "tl-015-morning-highway",
    source: "007_IMG_0263_morning_highway_update.MOV",
    section: "Pennsylvania Road",
    targetDuration: 16,
    role: "a_roll",
    sourceIn: 21,
    sourceOut: 44,
    notes: "Called David, three and a half hours left, feeling energetic.",
  },
  {
    id: "tl-016-pennsylvania-scenery",
    source: "008_IMG_0264_pennsylvania_scenery.MOV",
    section: "Pennsylvania Road",
    targetDuration: 10,
    role: "ambient",
    sourceIn: 0,
    sourceOut: 16,
    notes: "Scenic road montage; let it breathe.",
  },
  {
    id: "tl-017-drive-broll-hills",
    source: "009_IMG_0265_drive_broll_1.MOV",
    section: "Pennsylvania Road",
    targetDuration: 10,
    role: "ambient",
    sourceIn: 0,
    sourceOut: 16,
    notes: "Highway and hill b-roll under music.",
  },
  {
    id: "tl-018-woods-almost-there",
    source: "011_IMG_0267_in_the_woods_almost_there.MOV",
    section: "Pennsylvania Road",
    targetDuration: 18,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 20,
    notes: "In the woods and almost there.",
  },
  {
    id: "tl-019-big-mac-gag",
    source: "012_IMG_0268_double_big_mac_lunch.MOV",
    section: "Pennsylvania Road",
    targetDuration: 4,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 6,
    notes: "Optional quick hunger gag.",
  },
  {
    id: "tl-020-keyboard-21-arrival",
    source: "013_IMG_0269_keyboard_21_intro.MOV",
    section: "Factory",
    targetDuration: 8,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 7,
    notes: "Arrival: keyboard number 21.",
  },
  {
    id: "tl-021-keyboard-action-broll",
    source: "013_IMG_0269_keyboard_21_intro.MOV",
    section: "Factory",
    targetDuration: 14,
    role: "b_roll",
    sourceIn: 0,
    sourceOut: 40,
    notes: "Exposed action, keys, and workshop proof.",
  },
  {
    id: "tl-022-ds55-on-steinway",
    source: "018_IMG_0274_ds_size_lineup_on_steinway.MOV",
    section: "Factory",
    targetDuration: 30,
    role: "b_roll",
    sourceIn: 0,
    sourceOut: 43,
    notes: "DS 5.5 on Steinway B and DS 4.0 range.",
  },
  {
    id: "tl-023-size-lineup-proof",
    source: "018_IMG_0274_ds_size_lineup_on_steinway.MOV",
    section: "Factory",
    targetDuration: 20,
    role: "b_roll",
    sourceIn: 49,
    sourceOut: 72,
    textOverlay: "DS size lineup",
    notes: "Clearest size-comparison proof.",
  },
  {
    id: "tl-024-ds55-pickup-playing",
    source: "019_IMG_0275_ds55_pickup_and_wrap.MOV",
    section: "Factory",
    targetDuration: 27,
    role: "b_roll",
    sourceIn: 0,
    sourceOut: 150,
    notes: "DS 5.5 identification plus hands-on playing/testing.",
  },
  {
    id: "tl-025-athena-internals",
    source: "027_IMG_0283_athena_internals_reconnaissance.MOV",
    section: "Factory",
    targetDuration: 35,
    role: "b_roll",
    sourceIn: 0,
    sourceOut: 64,
    notes: "Technical tour: sound module, board, speakers, internals.",
  },
  {
    id: "tl-026-technical-stills",
    source: "technical-keyboard-stills",
    section: "Factory",
    targetDuration: 15,
    role: "still",
    notes: "Freeze-frame inserts of keys, action, and internals.",
  },
  {
    id: "tl-027-leaving-factory",
    source: "041_IMG_0297_ds60_ds55_car_monologue.MOV",
    section: "Main Argument",
    targetDuration: 20,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 36,
    notes: "Leaving with DS 6.0 and DS 5.5.",
  },
  {
    id: "tl-028-full-size-strain",
    source: "041_IMG_0297_ds60_ds55_car_monologue.MOV",
    section: "Main Argument",
    targetDuration: 27,
    role: "a_roll",
    sourceIn: 36,
    sourceOut: 77,
    textOverlay: "MY EXPERIENCE / FOR MY HAND SIZE",
    notes: "Full-size keyboard created strained wrist-based technique.",
  },
  {
    id: "tl-029-smaller-keys-technique",
    source: "041_IMG_0297_ds60_ds55_car_monologue.MOV",
    section: "Main Argument",
    targetDuration: 28,
    role: "a_roll",
    sourceIn: 94,
    sourceOut: 125,
    notes: "Smaller keys help intervals and finger technique.",
  },
  {
    id: "tl-030-healthier-foundation",
    source: "041_IMG_0297_ds60_ds55_car_monologue.MOV",
    section: "Main Argument",
    targetDuration: 28,
    role: "a_roll",
    sourceIn: 125,
    sourceOut: 151,
    notes: "Changes the piano experience; healthier foundation and less strain.",
  },
  {
    id: "tl-031-ds-standard-universities",
    source: "041_IMG_0297_ds60_ds55_car_monologue.MOV",
    section: "Main Argument",
    targetDuration: 37,
    role: "a_roll",
    sourceIn: 192,
    sourceOut: 227,
    textOverlay: "DS standard",
    notes: "DS standard and university use as a differentiating factor.",
  },
  {
    id: "tl-032-lake-transition",
    source: "042_IMG_0298_tionesta_lake_cutaway.MOV",
    section: "Trip Fights Back",
    targetDuration: 7,
    role: "ambient",
    sourceIn: 0,
    sourceOut: 9,
    notes: "Calm lake transition after dense argument.",
  },
  {
    id: "tl-033-lake-overlook",
    source: "043_IMG_0299_lake_overlook_broll.MOV",
    section: "Trip Fights Back",
    targetDuration: 6,
    role: "ambient",
    sourceIn: 0,
    sourceOut: 18,
    notes: "Overlook b-roll under music.",
  },
  {
    id: "tl-034-mileage-beat",
    source: "044_IMG_0300_177777_mileage.MOV",
    section: "Trip Fights Back",
    targetDuration: 4,
    role: "b_roll",
    sourceIn: 0,
    sourceOut: 6,
    notes: "Tiny weird road beat; optional.",
  },
  {
    id: "tl-035-hotel-breakdown",
    source: "048_IMG_0304_hotel_car_broke_down.MOV",
    section: "Trip Fights Back",
    targetDuration: 20,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 42,
    notes: "Hotel, car broke down, saga continues.",
  },
  {
    id: "tl-036-car-fixed",
    source: "049_IMG_0305_car_fixed_heading_home.MOV",
    section: "Trip Fights Back",
    targetDuration: 16,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 19,
    notes: "Car fixed; loose battery connection.",
  },
  {
    id: "tl-037-return-drive-beautiful",
    source: "050_IMG_0306_beautiful_return_drive.MOV",
    section: "Trip Fights Back",
    targetDuration: 6,
    role: "ambient",
    sourceIn: 0,
    sourceOut: 12,
    notes: "Beautiful return drive into home payoff.",
  },
  {
    id: "tl-038-highway-home",
    source: "053_IMG_0309_highway_home_broll.MOV",
    section: "Trip Fights Back",
    targetDuration: 6,
    role: "ambient",
    sourceIn: 0,
    sourceOut: 12,
    notes: "Highway home b-roll under music.",
  },
  {
    id: "tl-039-home-setup",
    source: "054_IMG_0310_home_ds60_ds55_explanation.MOV",
    section: "Home Payoff",
    targetDuration: 25,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 30,
    notes: "At home with DS 6.0 and DS 5.5; keys are what matter.",
  },
  {
    id: "tl-040-ds60-history",
    source: "054_IMG_0310_home_ds60_ds55_explanation.MOV",
    section: "Home Payoff",
    targetDuration: 25,
    role: "a_roll",
    sourceIn: 43,
    sourceOut: 65,
    notes: "DS 6.0 history and proper weighting.",
  },
  {
    id: "tl-041-p056-home-comparison",
    source: "056_PICKUP_hand_key_comparison.MOV",
    section: "Home Payoff",
    targetDuration: 5,
    role: "placeholder",
    textOverlay: "P056",
    notes: "Placeholder for hand/key comparison insert.",
  },
  {
    id: "tl-042-ds55-valid",
    source: "054_IMG_0310_home_ds60_ds55_explanation.MOV",
    section: "Home Payoff",
    targetDuration: 33,
    role: "a_roll",
    sourceIn: 71,
    sourceOut: 114,
    notes: "DS 5.5 is valid; smaller hands may benefit.",
  },
  {
    id: "tl-043-current-take-chart",
    source: "054_IMG_0310_home_ds60_ds55_explanation.MOV",
    section: "Home Payoff",
    targetDuration: 32,
    role: "a_roll",
    sourceIn: 126,
    sourceOut: 205,
    textOverlay: "My current take",
    notes: "Technique improved; update recommendations; try both sizes.",
  },
  {
    id: "tl-044-ds-standard-home",
    source: "054_IMG_0310_home_ds60_ds55_explanation.MOV",
    section: "Home Payoff",
    targetDuration: 35,
    role: "a_roll",
    sourceIn: 221,
    sourceOut: 296,
    textOverlay: "DS standard / university instruments",
    notes: "Why DS standard matters for serious study and universities.",
  },
  {
    id: "tl-045-closing-recommendation",
    source: "054_IMG_0310_home_ds60_ds55_explanation.MOV",
    section: "Closing",
    targetDuration: 13,
    role: "a_roll",
    sourceIn: 296,
    sourceOut: 312,
    notes: "Closing recommendation: buy a DS-sized keyboard.",
  },
  {
    id: "tl-046-final-hook",
    source: "056_PICKUP_hand_key_comparison.MOV",
    section: "Closing",
    targetDuration: 7,
    role: "placeholder",
    textOverlay: "Part 3: DS 6.0 vs DS 5.5 comparison?",
    notes: "Final still/demo placeholder until the pickup is recorded.",
  },
];

export const pass6TimelineSeed: SeedTimelineItem[] = [
  {
    id: "p6-001-late-night-trip-setup",
    source: "001_IMG_0256_0142am_trip_setup.MOV",
    section: "Cold Open",
    targetDuration: 8,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 8,
    notes: "V3: cold open keeps original camera audio.",
  },
  {
    id: "p6-002-home-payoff-flash",
    source: "054_IMG_0310_home_ds60_ds55_explanation.MOV",
    section: "Cold Open",
    targetDuration: 8,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 8,
    notes: "V3: early home payoff flash with original audio.",
  },
  {
    id: "p6-003-p056-cold-placeholder",
    source: "title-card-v3-p056-cold",
    section: "Cold Open",
    targetDuration: 3,
    role: "placeholder",
    textOverlay: "P056 PLACEHOLDER\nHand/key comparison flash",
    notes: "V3: placeholder card until the pickup is recorded.",
  },
  {
    id: "p6-004-cold-title-card",
    source: "title-card-v3-road-keyboard",
    section: "Cold Open",
    targetDuration: 5,
    role: "title_card",
    textOverlay: "I drove overnight for a keyboard\nmost pianists have never tried.",
    notes: "V3: title card from render script.",
  },
  {
    id: "p6-005-front-facing-intro",
    source: "055_PICKUP_front_facing_intro.MOV",
    section: "Set Up",
    targetDuration: 22,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 22,
    notes: "V3: coarse shortened intro; still needs word-level cleanup.",
  },
  {
    id: "p6-006-vo01-late-night-still",
    source: "90_Reference_Frames/IMG_0256.jpg",
    section: "VO 01 Late-Night Drive",
    targetDuration: 4,
    role: "still",
    notes: "V3: VO 01 with low music bed; no speaking clip audio underneath.",
  },
  {
    id: "p6-007-vo01-technical-still",
    source: "04_Keyboards_Technical_Stills/030_IMG_0286_technical_keyboard_still.JPG",
    section: "VO 01 Late-Night Drive",
    targetDuration: 5,
    role: "still",
    rotationOverride: 270,
    notes: "V3: VO 01/music over rotated technical still.",
  },
  {
    id: "p6-008-vo01-rainy-drive",
    source: "010_IMG_0266_drive_broll_2.MOV",
    section: "VO 01 Late-Night Drive",
    targetDuration: 6,
    role: "ambient",
    sourceIn: 0,
    sourceOut: 6,
    notes: "V3: VO 01/music over silent drive b-roll.",
  },
  {
    id: "p6-009-vo01-ds-lineup",
    source: "018_IMG_0274_ds_size_lineup_on_steinway.MOV",
    section: "VO 01 Late-Night Drive",
    targetDuration: 8,
    role: "b_roll",
    sourceIn: 49,
    sourceOut: 57,
    rotationOverride: 270,
    notes: "V3: VO 01/music over rotated DS lineup b-roll.",
  },
  {
    id: "p6-010-ds-size-lineup-setup",
    source: "018_IMG_0274_ds_size_lineup_on_steinway.MOV",
    section: "Set Up",
    targetDuration: 16,
    role: "b_roll",
    sourceIn: 49,
    sourceOut: 65,
    rotationOverride: 270,
    notes: "V3: clear size setup, rotated counterclockwise.",
  },
  {
    id: "p6-011-vo02-gas-station",
    source: "002_IMG_0257_hagerstown_gas_station.MOV",
    section: "VO 02 Gas Station",
    targetDuration: 6,
    role: "ambient",
    sourceIn: 0,
    sourceOut: 6,
    rotationOverride: 90,
    notes: "V3: VO 02/music over silent rotated gas station b-roll.",
  },
  {
    id: "p6-012-vo02-snack-still",
    source: "90_Reference_Frames/IMG_0258.jpg",
    section: "VO 02 Gas Station",
    targetDuration: 3,
    role: "still",
    notes: "V3: VO 02/music over snack still.",
  },
  {
    id: "p6-013-vo02-snacks-broll",
    source: "003_IMG_0258_road_trip_snacks_no_caffeine.MOV",
    section: "VO 02 Gas Station",
    targetDuration: 5,
    role: "b_roll",
    sourceIn: 103,
    sourceOut: 108,
    notes: "V3: VO 02/music over silent snack b-roll.",
  },
  {
    id: "p6-014-vo02-car-nap-still",
    source: "90_Reference_Frames/IMG_0260.jpg",
    section: "VO 02 Gas Station",
    targetDuration: 3,
    role: "still",
    notes: "V3: VO 02/music over car nap still.",
  },
  {
    id: "p6-015-snack-vlog-open",
    source: "003_IMG_0258_road_trip_snacks_no_caffeine.MOV",
    section: "Overnight Drive",
    targetDuration: 6,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 6,
    notes: "V3: preserves snack vlog beat with original audio.",
  },
  {
    id: "p6-016-snack-vlog-gag",
    source: "003_IMG_0258_road_trip_snacks_no_caffeine.MOV",
    section: "Overnight Drive",
    targetDuration: 5,
    role: "a_roll",
    sourceIn: 19,
    sourceOut: 24,
    notes: "V3: preserves snack vlog beat with original audio.",
  },
  {
    id: "p6-017-waking-after-car-nap",
    source: "005_IMG_0260_waking_up_after_car_nap.MOV",
    section: "Overnight Drive",
    targetDuration: 6,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 6,
    notes: "V3: original audio kept before VO montage.",
  },
  {
    id: "p6-018-car-nap-recovery-open",
    source: "006_IMG_0261_car_nap_recovery_drive_resumes.MOV",
    section: "Overnight Drive",
    targetDuration: 5,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 5,
    notes: "V3: original audio kept before VO montage.",
  },
  {
    id: "p6-019-car-nap-recovery-drive",
    source: "006_IMG_0261_car_nap_recovery_drive_resumes.MOV",
    section: "Overnight Drive",
    targetDuration: 4,
    role: "a_roll",
    sourceIn: 29,
    sourceOut: 33,
    notes: "V3: original audio kept before VO montage.",
  },
  {
    id: "p6-020-vo03-nap-still",
    source: "90_Reference_Frames/IMG_0260.jpg",
    section: "VO 03 Car Nap",
    targetDuration: 3,
    role: "still",
    notes: "V3: VO 03/music over still, not over speaking audio.",
  },
  {
    id: "p6-021-vo03-recovery-still",
    source: "90_Reference_Frames/IMG_0261.jpg",
    section: "VO 03 Car Nap",
    targetDuration: 3,
    role: "still",
    notes: "V3: VO 03/music over still, not over speaking audio.",
  },
  {
    id: "p6-022-vo03-rainy-drive",
    source: "010_IMG_0266_drive_broll_2.MOV",
    section: "VO 03 Car Nap",
    targetDuration: 8,
    role: "ambient",
    sourceIn: 0,
    sourceOut: 8,
    notes: "V3: rainy drive moved later and used under VO 03/music.",
  },
  {
    id: "p6-023-morning-highway-update",
    source: "007_IMG_0263_morning_highway_update.MOV",
    section: "Pennsylvania Road",
    targetDuration: 10,
    role: "a_roll",
    sourceIn: 21,
    sourceOut: 31,
    notes: "V3: speaking clip keeps original audio.",
  },
  {
    id: "p6-024-vo04-pennsylvania-scenery",
    source: "008_IMG_0264_pennsylvania_scenery.MOV",
    section: "VO 04 Pennsylvania Road",
    targetDuration: 8,
    role: "ambient",
    sourceIn: 0,
    sourceOut: 8,
    notes: "V3: VO 04/music over silent road b-roll.",
  },
  {
    id: "p6-025-vo04-drive-broll-hills",
    source: "009_IMG_0265_drive_broll_1.MOV",
    section: "VO 04 Pennsylvania Road",
    targetDuration: 7,
    role: "ambient",
    sourceIn: 0,
    sourceOut: 7,
    notes: "V3: VO 04/music over silent road b-roll.",
  },
  {
    id: "p6-026-vo04-woods-still",
    source: "90_Reference_Frames/IMG_0267.jpg",
    section: "VO 04 Pennsylvania Road",
    targetDuration: 5,
    role: "still",
    notes: "V3: VO 04/music over almost-there still.",
  },
  {
    id: "p6-027-woods-almost-there",
    source: "011_IMG_0267_in_the_woods_almost_there.MOV",
    section: "Pennsylvania Road",
    targetDuration: 12,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 12,
    notes: "V3: almost-there speaking clip keeps original audio.",
  },
  {
    id: "p6-028-big-mac-gag",
    source: "012_IMG_0268_double_big_mac_lunch.MOV",
    section: "Pennsylvania Road",
    targetDuration: 4,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 4,
    notes: "V3: quick lunch beat with original audio.",
  },
  {
    id: "p6-029-keyboard-21-arrival",
    source: "013_IMG_0269_keyboard_21_intro.MOV",
    section: "Factory",
    targetDuration: 7,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 7,
    notes: "V3: arrival/key number 21 beat.",
  },
  {
    id: "p6-030-keyboard-action-broll",
    source: "013_IMG_0269_keyboard_21_intro.MOV",
    section: "Factory",
    targetDuration: 10,
    role: "b_roll",
    sourceIn: 7,
    sourceOut: 17,
    notes: "V3: workshop/action b-roll.",
  },
  {
    id: "p6-031-ds55-on-steinway",
    source: "018_IMG_0274_ds_size_lineup_on_steinway.MOV",
    section: "Factory",
    targetDuration: 12,
    role: "b_roll",
    sourceIn: 0,
    sourceOut: 12,
    rotationOverride: 270,
    notes: "V3: rotated DS lineup footage.",
  },
  {
    id: "p6-032-ds55-size-range",
    source: "018_IMG_0274_ds_size_lineup_on_steinway.MOV",
    section: "Factory",
    targetDuration: 10,
    role: "b_roll",
    sourceIn: 25,
    sourceOut: 35,
    rotationOverride: 270,
    notes: "V3: rotated DS size range footage.",
  },
  {
    id: "p6-033-size-lineup-proof",
    source: "018_IMG_0274_ds_size_lineup_on_steinway.MOV",
    section: "Factory",
    targetDuration: 15,
    role: "b_roll",
    sourceIn: 49,
    sourceOut: 64,
    rotationOverride: 270,
    notes: "V3: rotated clearest size-comparison proof.",
  },
  {
    id: "p6-034-ds55-pickup-open",
    source: "019_IMG_0275_ds55_pickup_and_wrap.MOV",
    section: "Factory",
    targetDuration: 10,
    role: "b_roll",
    sourceIn: 0,
    sourceOut: 10,
    notes: "V3: DS 5.5 pickup/wrap beat.",
  },
  {
    id: "p6-035-ds55-pickup-later",
    source: "019_IMG_0275_ds55_pickup_and_wrap.MOV",
    section: "Factory",
    targetDuration: 25,
    role: "b_roll",
    sourceIn: 60,
    sourceOut: 85,
    notes: "V3: DS 5.5 hands-on/pickup footage.",
  },
  {
    id: "p6-036-athena-internals-open",
    source: "027_IMG_0283_athena_internals_reconnaissance.MOV",
    section: "Factory",
    targetDuration: 12,
    role: "b_roll",
    sourceIn: 0,
    sourceOut: 12,
    rotationOverride: 270,
    notes: "V3: rotated Athena internals footage.",
  },
  {
    id: "p6-037-athena-internals-later",
    source: "027_IMG_0283_athena_internals_reconnaissance.MOV",
    section: "Factory",
    targetDuration: 15,
    role: "b_roll",
    sourceIn: 29,
    sourceOut: 44,
    rotationOverride: 270,
    notes: "V3: rotated Athena internals footage.",
  },
  {
    id: "p6-038-technical-still-030",
    source: "04_Keyboards_Technical_Stills/030_IMG_0286_technical_keyboard_still.JPG",
    section: "Factory",
    targetDuration: 3,
    role: "still",
    rotationOverride: 270,
    notes: "V3: rotated technical still insert.",
  },
  {
    id: "p6-039-technical-still-031",
    source: "04_Keyboards_Technical_Stills/031_IMG_0287_technical_keyboard_still.JPG",
    section: "Factory",
    targetDuration: 3,
    role: "still",
    rotationOverride: 270,
    notes: "V3: rotated technical still insert.",
  },
  {
    id: "p6-040-technical-still-032",
    source: "04_Keyboards_Technical_Stills/032_IMG_0288_technical_keyboard_still.JPG",
    section: "Factory",
    targetDuration: 3,
    role: "still",
    rotationOverride: 270,
    notes: "V3: rotated technical still insert.",
  },
  {
    id: "p6-041-main-argument-card",
    source: "title-card-v3-main-argument",
    section: "Main Argument",
    targetDuration: 3,
    role: "title_card",
    textOverlay: "The real reason key size matters",
    notes: "V3: section card.",
  },
  {
    id: "p6-042-main-argument-1",
    source: "041_IMG_0297_ds60_ds55_car_monologue.MOV",
    section: "Main Argument",
    targetDuration: 24,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 24,
    notes: "V3: main argument with original camera audio.",
  },
  {
    id: "p6-043-main-argument-2",
    source: "041_IMG_0297_ds60_ds55_car_monologue.MOV",
    section: "Main Argument",
    targetDuration: 25,
    role: "a_roll",
    sourceIn: 36,
    sourceOut: 61,
    notes: "V3: main argument with original camera audio.",
  },
  {
    id: "p6-044-main-argument-3",
    source: "041_IMG_0297_ds60_ds55_car_monologue.MOV",
    section: "Main Argument",
    targetDuration: 24,
    role: "a_roll",
    sourceIn: 94,
    sourceOut: 118,
    notes: "V3: main argument with original camera audio.",
  },
  {
    id: "p6-045-main-argument-4",
    source: "041_IMG_0297_ds60_ds55_car_monologue.MOV",
    section: "Main Argument",
    targetDuration: 22,
    role: "a_roll",
    sourceIn: 125,
    sourceOut: 147,
    notes: "V3: main argument with original camera audio.",
  },
  {
    id: "p6-046-main-argument-5",
    source: "041_IMG_0297_ds60_ds55_car_monologue.MOV",
    section: "Main Argument",
    targetDuration: 30,
    role: "a_roll",
    sourceIn: 192,
    sourceOut: 222,
    notes: "V3: main argument with original camera audio.",
  },
  {
    id: "p6-047-vo05-lake-cutaway",
    source: "042_IMG_0298_tionesta_lake_cutaway.MOV",
    section: "VO 05 Lake Pause",
    targetDuration: 7,
    role: "ambient",
    sourceIn: 0,
    sourceOut: 7,
    notes: "V3: VO 05/music over silent lake cutaway.",
  },
  {
    id: "p6-048-vo05-lake-overlook",
    source: "043_IMG_0299_lake_overlook_broll.MOV",
    section: "VO 05 Lake Pause",
    targetDuration: 7,
    role: "ambient",
    sourceIn: 0,
    sourceOut: 7,
    notes: "V3: VO 05/music over silent lake overlook.",
  },
  {
    id: "p6-049-vo05-mileage",
    source: "044_IMG_0300_177777_mileage.MOV",
    section: "VO 05 Lake Pause",
    targetDuration: 6,
    role: "b_roll",
    sourceIn: 0,
    sourceOut: 6,
    notes: "V3: mileage beat extended to 6s under VO 05/music.",
  },
  {
    id: "p6-050-hotel-breakdown",
    source: "048_IMG_0304_hotel_car_broke_down.MOV",
    section: "Trip Fights Back",
    targetDuration: 8,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 8,
    notes: "V3: breakdown speaking clip moved later and keeps original audio.",
  },
  {
    id: "p6-051-vo06-breakdown-still",
    source: "90_Reference_Frames/IMG_0304.jpg",
    section: "VO 06 Return",
    targetDuration: 4,
    role: "still",
    notes: "V3: VO 06/music over hotel breakdown still.",
  },
  {
    id: "p6-052-vo06-car-fixed",
    source: "049_IMG_0305_car_fixed_heading_home.MOV",
    section: "VO 06 Return",
    targetDuration: 8,
    role: "ambient",
    sourceIn: 0,
    sourceOut: 8,
    notes: "V3: VO 06/music over silent car-fixed b-roll.",
  },
  {
    id: "p6-053-vo06-return-drive",
    source: "050_IMG_0306_beautiful_return_drive.MOV",
    section: "VO 06 Return",
    targetDuration: 6,
    role: "ambient",
    sourceIn: 0,
    sourceOut: 6,
    notes: "V3: VO 06/music over silent return-drive b-roll.",
  },
  {
    id: "p6-054-vo06-highway-home",
    source: "053_IMG_0309_highway_home_broll.MOV",
    section: "VO 06 Return",
    targetDuration: 8,
    role: "ambient",
    sourceIn: 0,
    sourceOut: 8,
    notes: "V3: VO 06/music over silent highway-home b-roll.",
  },
  {
    id: "p6-055-home-setup",
    source: "054_IMG_0310_home_ds60_ds55_explanation.MOV",
    section: "Home Payoff",
    targetDuration: 20,
    role: "a_roll",
    sourceIn: 0,
    sourceOut: 20,
    notes: "V3: home payoff with original camera audio.",
  },
  {
    id: "p6-056-ds60-history",
    source: "054_IMG_0310_home_ds60_ds55_explanation.MOV",
    section: "Home Payoff",
    targetDuration: 18,
    role: "a_roll",
    sourceIn: 43,
    sourceOut: 61,
    notes: "V3: DS 6.0 history/proper weighting.",
  },
  {
    id: "p6-057-p056-home-placeholder",
    source: "title-card-v3-p056-home",
    section: "Home Payoff",
    targetDuration: 5,
    role: "placeholder",
    textOverlay: "P056 PLACEHOLDER\nStandard vs DS 6.0 vs DS 5.5",
    notes: "V3: placeholder card until the hand/key comparison pickup is recorded.",
  },
  {
    id: "p6-058-ds55-valid",
    source: "054_IMG_0310_home_ds60_ds55_explanation.MOV",
    section: "Home Payoff",
    targetDuration: 24,
    role: "a_roll",
    sourceIn: 71,
    sourceOut: 95,
    notes: "V3: DS 5.5 validity explanation.",
  },
  {
    id: "p6-059-current-take-card",
    source: "title-card-v3-current-take",
    section: "Home Payoff",
    targetDuration: 5,
    role: "title_card",
    textOverlay: "My current take\nTry DS 6.0 and DS 5.5 if possible.\nUnder ~8.2 inches: consider DS 5.5 too.",
    notes: "V3: recommendation card.",
  },
  {
    id: "p6-060-home-technique-1",
    source: "054_IMG_0310_home_ds60_ds55_explanation.MOV",
    section: "Home Payoff",
    targetDuration: 12,
    role: "a_roll",
    sourceIn: 126,
    sourceOut: 138,
    notes: "V3: home payoff continued.",
  },
  {
    id: "p6-061-home-technique-2",
    source: "054_IMG_0310_home_ds60_ds55_explanation.MOV",
    section: "Home Payoff",
    targetDuration: 18,
    role: "a_roll",
    sourceIn: 154,
    sourceOut: 172,
    notes: "V3: home payoff continued.",
  },
  {
    id: "p6-062-home-technique-3",
    source: "054_IMG_0310_home_ds60_ds55_explanation.MOV",
    section: "Home Payoff",
    targetDuration: 18,
    role: "a_roll",
    sourceIn: 178,
    sourceOut: 196,
    notes: "V3: home payoff continued.",
  },
  {
    id: "p6-063-ds-standard-home",
    source: "054_IMG_0310_home_ds60_ds55_explanation.MOV",
    section: "Home Payoff",
    targetDuration: 35,
    role: "a_roll",
    sourceIn: 221,
    sourceOut: 256,
    notes: "V3: DS standard/university instruments segment.",
  },
  {
    id: "p6-064-closing-recommendation",
    source: "054_IMG_0310_home_ds60_ds55_explanation.MOV",
    section: "Closing",
    targetDuration: 13,
    role: "a_roll",
    sourceIn: 296,
    sourceOut: 309,
    notes: "V3: closing recommendation.",
  },
  {
    id: "p6-065-final-hook",
    source: "title-card-v3-final-hook",
    section: "Closing",
    targetDuration: 7,
    role: "title_card",
    textOverlay: "Part 3:\nDS 6.0 vs DS 5.5 comparison?",
    notes: "V3: final hook card.",
  },
];

function carryToPass7(item: SeedTimelineItem): SeedTimelineItem {
  return {
    ...item,
    id: item.id.replace(/^p6-/, "p7-"),
    notes: item.notes.replace(/^V3:/, "V4:"),
  };
}

export const pass7TimelineSeed: SeedTimelineItem[] = pass6TimelineSeed.flatMap((item) => {
  switch (item.id) {
    case "p6-001-late-night-trip-setup":
      return [
        {
          ...carryToPass7(item),
          targetDuration: 16,
          sourceOut: 16,
          notes: "V4: extended the cold-open setup so the line does not cut off abruptly.",
        },
      ];

    case "p6-003-p056-cold-placeholder":
      return [
        {
          ...carryToPass7(item),
          notes: "V4: placeholder card with low travel music underneath.",
        },
      ];

    case "p6-004-cold-title-card":
      return [
        {
          ...carryToPass7(item),
          notes: "V4: title card with low travel music underneath.",
        },
      ];

    case "p6-005-front-facing-intro":
      return [
        {
          ...carryToPass7(item),
          id: "p7-005-front-facing-intro-open",
          targetDuration: 6,
          sourceIn: 0,
          sourceOut: 6,
          notes: "V4: fine-edit intro opening; keeps the clean part-two setup line.",
        },
        {
          ...carryToPass7(item),
          id: "p7-006-front-facing-intro-clean-thesis",
          targetDuration: 17,
          sourceIn: 13.5,
          sourceOut: 30.5,
          notes:
            "V4: jumps past the false start and cuts before the repeated smaller-hands line.",
        },
      ];

    case "p6-008-vo01-rainy-drive":
      return [
        {
          ...carryToPass7(item),
          id: "p7-009-vo01-sheetz-stop",
          source: "004_IMG_0259_sheets_stop_middle_of_nowhere.MOV",
          sourceIn: 0,
          sourceOut: 6,
          targetDuration: 6,
          notes:
            "V4: replaced early rainy-drive footage so IMG_0266 only appears after the car-nap beat.",
        },
      ];

    case "p6-049-vo05-mileage":
      return [
        {
          ...carryToPass7(item),
          notes: "V4: keeps the full available mileage clip under VO 05/music.",
        },
        {
          id: "p7-049b-vo05-mileage-hold",
          source: "90_Reference_Frames/IMG_0300.jpg",
          section: item.section,
          targetDuration: 2,
          role: "still",
          notes:
            "V4: adds a 2s still hold so the mileage beat no longer feels like it cuts off too fast.",
        },
      ];

    default:
      return [carryToPass7(item)];
  }
});
